static Procs sort_procs(Procs);
static void print_indent(int);
static void print_constant(Constant, int);
static void print_expr(Expr, int);
static void print_write_expr(Expr, int, char*);
static void print_write_constant(Constant);
static void print_exprs(Exprs);
static void print_stmt(Stmt, int, char*);
static void print_stmts(Stmts, int, char*);
static void print_procs(Procs);
static void print_proc(Proc);
static void print_header(Header);
static void print_decls(Decls, int, char*);
static void print_decl(Decl, int, char*);
static void print_assign(Assign, int);
//static void print_assign_array(Assign, int);
static Type print_cond(Expr, int, char*, int);
//static void print_while(While, int);
static void print_params(Params);
static void print_pram(Param);
static void print_write(Stmt, int, char*);
static void print_read(Stmt, int, char*);
static void print_read_array(Stmt, int);
static void print_fncall(Stmt, int);
static void print_intervals(Intervals);
static void print_interval(Interval);
void pretty_prog(FILE *, Program);
int print_binop(Expr, int, char*);
void print_binop_string(int, int, int, int, int);
static Type getExprType(Expr, char*);
